<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find armmy_omnibot)/urdf/inertial_macros.xacro" />
    <xacro:include filename="$(find armmy_omnibot)/urdf/omni_wheel/omni_wheel.gazebo.xacro" />
    <xacro:include filename="$(find armmy_omnibot)/urdf/omni_wheel/omni_wheel.transmission.xacro" />
    <xacro:include filename="$(find armmy_omnibot)/urdf/roller/gz_roller.urdf.xacro" />

    <xacro:property name="wheel_thickness" value="0.0185" />
    <xacro:property name="wheel_radian" value="0.0175" />
    <xacro:property name="wheel_mass" value="0.05" />

    <xacro:macro name="wheel_v0" params="prefix parent *joint_origin *joint_axis">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <xacro:insert_block name="joint_origin" />
            <parent link="${parent}" />
            <child link="${prefix}_wheel_link" />
            <limit effort="100" velocity="100" />
            <xacro:insert_block name="joint_axis" />
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <mesh filename="package://armmy_omnibot/meshes/omni_wheel/wheel_assembly.dae"
                        scale="1 1 1" />
                </geometry>
                <!-- <material name="light_black" /> -->
            </visual>

            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
                radius="${wheel_radian}">
                <origin xyz="0 ${wheel_thickness/2} 0" rpy="1.570796327 0 0" />
            </xacro:inertial_cylinder>
        </link>

        <xacro:roller prefix="${prefix}" num="1">
            <!-- <origin xyz="0 0.0023125 0.0" rpy="0.0 0.0 0.0" /> -->
            <origin xyz="0 0.004625 0.0" rpy="0.0 0.0 0.0" />
            <!-- <origin xyz="0.015 0.1 0.0" rpy="0.0 0.0 0.0" /> -->
            <axis xyz="0.0 0.0 1.0" />
        </xacro:roller>
        <xacro:roller prefix="${prefix}" num="1_2">
            <!-- <origin xyz="0 0.0023125 0.0" rpy="0.0 0.0 0.0" /> -->
            <origin xyz="0 0.0185 0.0" rpy="0.0 0.0 0.0" />
            <!-- <origin xyz="0.015 0.1 0.0" rpy="0.0 0.0 0.0" /> -->
            <axis xyz="0.0 0.0 1.0" />
        </xacro:roller>
        <!-- <xacro:roller prefix="${prefix}" num="2">
            <origin xyz="0.0 0.0046 0.015" rpy="-1.0 0.0 0.0" />
            <axis xyz="-1.0 0.0 0.0" />
        </xacro:roller>
        <xacro:roller prefix="${prefix}" num="3">
            <origin xyz="-0.015 0.0046 0.0" rpy="-0.0 0.0 -1.0" />
            <axis xyz="-0.0 0.0 -1.0" />
        </xacro:roller>
        <xacro:roller prefix="${prefix}" num="4">
            <origin xyz="-0.0 0.0046 -0.015" rpy="1.0 0.0 -0.0" />
            <axis xyz="1.0 0.0 -0.0" />
        </xacro:roller>
        <xacro:roller prefix="${prefix}" num="5">
            <origin xyz="0.0106 0.0139 0.0106" rpy="-0.707107 0.0 0.707107" />
            <axis xyz="-0.707107 0.0 0.707107" />
        </xacro:roller>
        <xacro:roller prefix="${prefix}" num="6">
            <origin xyz="-0.0106 0.0139 0.0106" rpy="-0.707107 0.0 -0.707107" />
            <axis xyz="-0.707107 0.0 -0.707107" />
        </xacro:roller>
        <xacro:roller prefix="${prefix}" num="7">
            <origin xyz="-0.0106 0.0139 -0.0106" rpy="0.707107 0.0 -0.707107" />
            <axis xyz="0.707107 0.0 -0.707107" />
        </xacro:roller>
        <xacro:roller prefix="${prefix}" num="8">
            <origin xyz="0.0106 0.0139 -0.0106" rpy="0.707107 0.0 0.707107" />
            <axis xyz="0.707107 0.0 0.707107" />
        </xacro:roller> -->
    </xacro:macro>

</robot>