slam_toolbox:
  ros__parameters:
    use_sim_time: false  # Set to true if using simulation
    map_update_interval: 5.0
    resolution: 0.05
    max_range: 16.0
    publish_frame: map
    laser_scan_topic: /scan  # Change this to match your LiDAR topic
